# Generated by Django 2.1.7 on 2019-03-22 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uodgu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='guild',
        ),
        migrations.AlterField(
            model_name='sop',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sops', to='users.Guild'),
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
